version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
