services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      DEVELOPMENT_HOST: ${DEVELOPMENT_HOST}
      PRODUCTION_HOST: ${PRODUCTION_HOST}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
