DROP DATABASE IF EXISTS urlShortner;
CREATE DATABASE urlShortner;

-- Table: providers
CREATE TABLE public.providers (
    id smallint generated by default as identity not null,
    provider character varying not null,
    active boolean not null default true,
    code character varying not null,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint providers_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: roles
CREATE TABLE public.roles (
    id smallint generated by default as identity not null,
    role character varying not null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint roles_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: users
CREATE TABLE public.users (
    id smallint generated by default as identity not null,
    role_id bigint not null,
    email character varying not null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint users_pkey primary key (id),
    constraint users_unique_email_role unique (role_id, email),
    constraint users_role_id_fkey foreign key (role_id) references roles (id)
) TABLESPACE pg_default;

-- Table: user_metadata
CREATE TABLE public.user_metadata (
    id smallint generated by default as identity not null,
    user_id bigint not null,
    first_name character varying null,
    last_name character varying null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint user_metadata_pkey primary key (id),
    constraint user_metadata_user_id_fkey foreign key (user_id) references users (id)
) TABLESPACE pg_default;

-- Table: authentication_requests
CREATE TABLE public.authentication_requests (
    id smallint generated by default as identity not null,
    reference character varying not null,
    provider_id bigint not null,
    user_id bigint null,
    expiry timestamp without time zone not null,
    verified boolean not null default false,
    email character varying null,
    state character varying null,
    token character varying null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint authentication_requests_pkey primary key (id),
    constraint authentication_requests_provider_id_fkey foreign key (provider_id) references providers (id),
    constraint authentication_requests_user_id_fkey foreign key (user_id) references users (id)
) TABLESPACE pg_default;

-- Table: origins
CREATE TABLE public.origins (
  id smallint generated by default as identity not null,
    origin character varying not null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint origins_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: platforms
CREATE TABLE public.platforms (
    id smallint generated by default as identity not null,
    platform character varying not null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint platforms_pkey primary key (id)
) TABLESPACE pg_default;

-- Table: devices
CREATE TABLE public.devices (
    id smallint generated by default as identity not null,
    identifier character varying not null,
    origin_id bigint not null,
    platform_id bigint not null,
    app_version bigint not null,
    user_agent character varying null,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint devices_pkey primary key (id),
    constraint devices_unique_identifier_origin_platform unique (identifier, origin_id, platform_id),
    constraint devices_origin_id_fkey foreign key (origin_id) references origins (id),
    constraint devices_platform_id_fkey foreign key (platform_id) references platforms (id)
  ) TABLESPACE pg_default;

-- Table: sessions
CREATE TABLE public.sessions (
    id smallint generated by default as identity not null,
    user_id bigint not null,
    token character varying not null,
    device_id bigint not null,
    expiry timestamp without time zone not null default now(),
    active boolean not null default true,
    created_at timestamp without time zone not null default current_timestamp,
    updated_at timestamp without time zone null,
    deleted_at timestamp without time zone null,
    constraint sessions_pkey primary key (id),
    constraint sessions_device_id_fkey foreign key (device_id) references devices (id),
    constraint sessions_user_id_fkey foreign key (user_id) references users (id)
) TABLESPACE pg_default;

-- Data initialization
INSERT INTO public.roles (id, role) VALUES (1, 'user'), (2, 'admin');

INSERT INTO public.origins (id, origin) VALUES (1, 'urlShortner-ui');

INSERT INTO public.platforms (id, platform) VALUES 
(1, 'Web'),
(2, 'iOS'),
(3, 'Android');

INSERT INTO public.providers (id, provider, code) VALUES (1, 'Google', 'google');
